apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: expense-tracker-prod
resources:
  - ../../base
images:
  - name: REPLACE_ME/expense-tracker-backend
    newName: 259151461533.dkr.ecr.us-east-1.amazonaws.com/expense-tracker-backend
    newTag: <REAL_TAG>
