name: CI

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_REPOSITORY: expense-tracker-backend
  IMAGE_TAG: ${{ github.sha }}

jobs:

  lint-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: expense_tracker_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: npm
          cache-dependency-path: app/package-lock.json


      - name: Install dependencies
        working-directory: app
        run: npm ci


      - name: Wait for PostgreSQL
        env:
          PGPASSWORD: postgres
        run: |
          until pg_isready -h localhost -U postgres; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done


      - name: Show migration files
        working-directory: app
        run: |
          pwd
          ls -la
          ls -la migrations


      - name: Run database migrations
        working-directory: app
        env:
          NODE_ENV: test
          TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/expense_tracker_test
          JWT_SECRET: super-secret-passphrase
          JWT_EXPIRY: 1d
        run: |
          npm run migrate:test


      - name: Verify database tables
        env:
          PGPASSWORD: postgres
        run: |
          psql -h localhost -U postgres -d expense_tracker_test -c "\dt"


      - name: Lint
        working-directory: app
        run: |
          npx eslint . || true


      - name: Run tests
        working-directory: app
        env:
          NODE_ENV: test
          TEST_DATABASE_URL: postgresql://postgres:postgres@localhost:5432/expense_tracker_test
          JWT_SECRET: super-secret-passphrase
          JWT_EXPIRY: 1d
        run: |
          npm test



  build-scan-push:

    needs: lint-test

    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read


    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Debug GitHub Context
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}


      - name: Verify AWS Identity
        run: |
          aws sts get-caller-identity


      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2


      - name: Build Docker Image
        run: |
          docker build \
          -f docker/Dockerfile \
          -t $ECR_REPOSITORY:$IMAGE_TAG .

          docker tag \
          $ECR_REPOSITORY:$IMAGE_TAG \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

          docker tag \
          $ECR_REPOSITORY:$IMAGE_TAG \
          ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest


      - name: Scan Image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
          format: table
          severity: CRITICAL,HIGH
          exit-code: "0"


      - name: Push Image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:latest



      - name: Update Kubernetes Manifest
        run: |

          sed -i \
          "s|image: .*expense-tracker-backend.*|image: ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG|" \
          k8s/overlays/prod/kustomization.yaml


          git config user.name "github-actions"

          git config user.email "actions@github.com"


          git add k8s/overlays/prod/kustomization.yaml


          git commit \
          -m "chore: update image $IMAGE_TAG [skip ci]" \
          || echo "Nothing to commit"


          git push


